import Sidebar from "@/components/Sidebar";
import "./globals.css";
import Top from "@/components/Top";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`body`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
